package define

type D map[string]string
type H interface{}
type KeyWord struct {
	KeyWord string `json:"KeyWord"`
}
type M map[string]interface{}
type AutoGenerated struct {
	URL     string  `json:"Url"`
	Type    string  `json:"Type"`
	ID      string  `json:"Id"`
	Payload Payload `json:"Payload"`
}
type Payload struct {
	Title        string `json:"Title"`
	VideoShort   string `json:"VideoShort"`
	Pic          string `json:"Pic"`
	URL          string `json:"Url"`
	VideoPreview string `json:"VideoPreview"`
	VideoFormal  string `json:"VideoFormal"`
	Number       string `json:"Number"`
}

var VideoDataName = "VideoDataName.conf"

type VideoData struct {
	Data []AutoGenerated `json:"data"`
}

var ConfigName = "redis-client.conf"

type Connection struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
	Addr     string `json:"addr"`
	Port     string `json:"port"`
	UserName string `json:"userName"`
	PassWord string `json:"passWord"`
}

type Config struct {
	Connections []*Connection `json:"connections"`
}

type SearchResult struct {
	Hits     int64
	Start    int
	Query    string
	PrevFrom int
	NextFrom int
	Items    []interface{}
}
type Item struct {
	Url     string
	Type    string
	Id      string
	Payload interface{}
}

type LoginInfo struct {
	UserName string
	PassWord string
}
type PayloadJson struct {
	Title        string `json:"Title"`
	VideoShort   string `json:"VideoShort"`
	Pic          string `json:"Pic"`
	Url          string `json:"Url"`
	VideoPreview string `json:"VideoPreview"`
	VideoFormal  string `json:"VideoFormal"`
	Number       string `json:"Number"`
	ShortLocal   string `json:"ShortLocal"`
	PreviewLocal string `json:"PreviewLocal"`
	FormalLocal  string `json:"FormalLocal"`
	ImgLocal     string `json:"ImgLocal"`
	CreateTime   string `json:"CreateTime"`
	UserInput    string `json:"UserInput"`
	VideoType    string `json:"VideoType"`
	Description  string `json:"Description"`
}

type ItemJson struct {
	Url     string      `json:"Url"`
	Type    string      `json:"Type"`
	Id      string      `json:"Id"`
	Payload PayloadJson `json:"Payload"`
}

type DataJson struct {
	Hits  int        `json:"Hits"`
	Start int        `json:"Start"`
	Query string     `json:"Query"`
	Items []ItemJson `json:"Items"`
}
