// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';
import {define} from '../models';
import {menu} from '../models';

export function AddTask(arg1:string):Promise<utils.Response>;

export function BatchUploadFile():Promise<utils.Response>;

export function CheckFile(arg1:string):Promise<void>;

export function ConfigEdit(arg1:define.M):Promise<define.H>;

export function DeleteTask(arg1:string):Promise<utils.Response>;

export function ExportVideoList(arg1:string):Promise<define.H>;

export function FilterTasks(arg1:string):Promise<utils.Response>;

export function GetConfig():Promise<utils.Response>;

export function GetHomeInfo():Promise<define.M>;

export function GetSettingList():Promise<define.H>;

export function GetTaskList():Promise<utils.Response>;

export function Greet(arg1:string):Promise<string>;

export function InitConfig():Promise<void>;

export function InitLogin():Promise<void>;

export function InitPath():Promise<void>;

export function Menu():Promise<menu.Menu>;

export function OpenFolder(arg1:string):Promise<define.H>;

export function SearchKey(arg1:define.M):Promise<define.H>;

export function SetConfig(arg1:string):Promise<utils.Response>;

export function UpdateSettingList(arg1:any):Promise<define.H>;

export function UpdateTask(arg1:string):Promise<utils.Response>;

export function Upload(arg1:string,arg2:Array<boolean>):Promise<string>;

export function VideoCreate(arg1:any):Promise<define.H>;

export function VideoDelete(arg1:any):Promise<define.H>;

export function VideoGetNumber(arg1:any):Promise<define.H>;

export function VideoList():Promise<define.H>;

export function VideoManage(arg1:string):Promise<define.H>;
