// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['internal']['App']['AddTask'](arg1);
}

export function BatchUploadFile() {
  return window['go']['internal']['App']['BatchUploadFile']();
}

export function CheckFile(arg1) {
  return window['go']['internal']['App']['CheckFile'](arg1);
}

export function ConfigEdit(arg1) {
  return window['go']['internal']['App']['ConfigEdit'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['internal']['App']['DeleteTask'](arg1);
}

export function ExportVideoList(arg1) {
  return window['go']['internal']['App']['ExportVideoList'](arg1);
}

export function FilterTasks(arg1) {
  return window['go']['internal']['App']['FilterTasks'](arg1);
}

export function GetConfig() {
  return window['go']['internal']['App']['GetConfig']();
}

export function GetHomeInfo() {
  return window['go']['internal']['App']['GetHomeInfo']();
}

export function GetSettingList() {
  return window['go']['internal']['App']['GetSettingList']();
}

export function GetTaskList() {
  return window['go']['internal']['App']['GetTaskList']();
}

export function Greet(arg1) {
  return window['go']['internal']['App']['Greet'](arg1);
}

export function InitConfig() {
  return window['go']['internal']['App']['InitConfig']();
}

export function InitLogin() {
  return window['go']['internal']['App']['InitLogin']();
}

export function InitPath() {
  return window['go']['internal']['App']['InitPath']();
}

export function Menu() {
  return window['go']['internal']['App']['Menu']();
}

export function OpenFolder(arg1) {
  return window['go']['internal']['App']['OpenFolder'](arg1);
}

export function SearchKey(arg1) {
  return window['go']['internal']['App']['SearchKey'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['internal']['App']['SetConfig'](arg1);
}

export function UpdateSettingList(arg1) {
  return window['go']['internal']['App']['UpdateSettingList'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['internal']['App']['UpdateTask'](arg1);
}

export function Upload(arg1, arg2) {
  return window['go']['internal']['App']['Upload'](arg1, arg2);
}

export function VideoCreate(arg1) {
  return window['go']['internal']['App']['VideoCreate'](arg1);
}

export function VideoDelete(arg1) {
  return window['go']['internal']['App']['VideoDelete'](arg1);
}

export function VideoGetNumber(arg1) {
  return window['go']['internal']['App']['VideoGetNumber'](arg1);
}

export function VideoList() {
  return window['go']['internal']['App']['VideoList']();
}

export function VideoManage(arg1) {
  return window['go']['internal']['App']['VideoManage'](arg1);
}
